### ISSUE TITLE
Decouple from githooks?

### ISSUE THREAD

**Issue by ianwremmel** [naholyr/github-todos#13]
First off, this looks really helpful. Unfortunately, hooks aren't ideal for the workflow that I follow (and for various organizational reasons, that workflow can't be changed). Would it be possible to expose the core library so that grunt or gulp tasks could be written around it?

**Comment by naholyr** [comment]
Is there more work to do here? :dancer:

**Comment by ianwremmel** [comment]
I still suspect it could be useful to separate out the parse/rewrite code from the actual githook part, but I don't have a specific need at the moment, so yea, I think this can be closed.
