### ISSUE TITLE
Custom Host support

### ISSUE THREAD

**Issue by psykzz** [naholyr/github-todos#22]
Looks like if you have a self hosted version of github It fails with the message

```
Connection to 'github' failed
Error: 'repo': expected format 'user/repository'
```

**Comment by naholyr** [comment]
If the remote does not contain github.com it will indeed fail to guess. You can set this manually with `ght config repo user/repo` but then I'm not sure the tool is perfectly ready for hosted hubs

**Comment by psykzz** [comment]
What about if we change the `"github.host"`?

**Comment by naholyr** [comment]
It should do the trick, it's what it's there for at least ;) but I had no feedback. If it works well for you please let me know!

**Comment by psykzz** [comment]
Will do.

**Comment by naholyr** [comment]
Planned change: more doc about this use case

**Comment by psykzz** [comment]
So it worked well enough for me. Closing issue.
